events {}
http {
    upstream backend_up {
        server backend:8000;
    }
    upstream frontend_up {
        server frontend:3000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_up/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_pass http://frontend_up/;
            proxy_set_header Host $host;
        }

        gzip on;
        gzip_types text/plain application/json text/css application/javascript;
    }
}
